version: '3.5'

services:
  lsgapi:
    image: lsghost:test
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - test
    environment:
      ASPNETCORE_ENVIRONMENT: IntegrationTest
      ASPNETCORE_SERVERNAME: Dev01
  loggerworker:
    image: lsghost:test
    build:
      context: .
      dockerfile: Dockerfile
    
    restart: always
    
    networks:
      - test
    environment:
      ASPNETCORE_ENVIRONMENT: IntegrationTest
      ASPNETCORE_SERVERNAME: Dev01
  lsgfrontend:
    image: lsghost:test
    build:
      context: .
      dockerfile: Dockerfile
    
    restart: always
    
    networks:
      - test
    environment:
      ASPNETCORE_ENVIRONMENT: IntegrationTest
      ASPNETCORE_SERVERNAME: Dev01
  
  nats:
    image: nats:latest
    restart: always
    networks:
      - test
  redis:
    image: redis:latest
    restart: always
    networks:
      - test
  lsgtestdb:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      SA_PASSWORD: "5VckGdLyvC2zDK8e"
      ACCEPT_EULA: "Y"
    restart: always
    networks:
      - test
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    restart: always
    networks:
      - test

networks:
  test:
    name: tc_net
    driver: bridge
  